files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
  empty-line-between-blocks: 1
  extends-before-declarations: 0
  extends-before-mixins: 0
  function-name-format: 1
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 2
    - size: 2
  leading-zero: 0
  mixin-name-format: 1
  mixins-before-declarations: 0
  no-extends: 1
  no-ids: 1
  no-trailing-whitespace: 1
  no-qualifying-elements: 0
  one-declaration-per-line: 1
  single-line-per-selector: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
  quotes:
    - 1
    - style: double
  trailing-semicolon: 1
  variable-name-format: 1
resolvers:
  property-sort-order: 1
  attribute-quotes: 1
  border-zero: 1
  indentation: 1
syntax:
  include:
    - scss
    - sass
